Disable advice.objectNameWarning when rebasing
It looks like some of our tests are sometimes triggering this
advice and then failing because they didn't expect it.

For example this is a test error we get:

 --- FAIL: TestFailedUserRebaseConfirmableDueToGitError (0.17s)
    rebase_test.go:390:
        	Error Trace:	rebase_test.go:390
        	Error:      	"Auto-merging README.md
        	            	CONFLICT (content): Merge conflict in README.md
        	            	From ssh://gitaly/internal
        	            	 * branch            master     -> FETCH_HEAD
        	            	warning: refname '1942eed5cc108b19c7405106e81fa96125d0be22' is ambiguous.
        	            	Git normally never creates a ref that ends with 40 hex characters
        	            	because it will be ignored when you just specify 40-hex. These refs
        	            	may be created by mistake. For example,

        	            	  git switch -c $br $(git rev-parse ...)

        	            	where "$br" is somehow empty and a 40-hex ref is created. Please
        	            	examine these refs and maybe delete them. Turn this message off by
        	            	running "git config advice.objectNameWarning false"
error: could not apply eb8f5fb... Make whitespace changes versão 5.5
        	            	Resolve all conflicts manually, mark them as resolved with
        	            	"git add/rm <conflicted_files>", then run "git rebase --continue".
        	            	You can instead skip this commit: run "git rebase --skip".
        	            	To abort and get back to the state before "git rebase", run "git rebase --abort".
        	            	Could not apply eb8f5fb... Make whitespace changes versão 5.5
        	            	" does not contain "error: Failed to merge in the changes."